services:
  - type: web
    name: habit-tracker
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: habit-tracker-db
          property: connectionString

databases:
  - name: habit-tracker-db
    databaseName: habittracker
    user: habittracker